<%@ page language="java" contentType="text/javascript"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
var jsvar = {
  missingUserId: "<s:message code='missing.userid' />",
  missingPwd : "<s:message code='missing.pwd' />",
  missingEntry : "<s:message code='missing.entry' />",
  missingCat:"<s:message code='missing.cat' />",
  headerInput:"<s:message code='header.input' />",
  headerEntryNew:"<s:message code='newEntry' />",
  headerEntryCreate:"<s:message code='createEntry' />",
  headerEntryEdit:"<s:message code='editEntry' />",
  headerEntryView : "<s:message code='viewEntry' />",
  headerEntryUpdate : "<s:message code='updateEntry' />",
  headerCatCreate : "<s:message code='header.cat.create' />" ,
  headerCatEdit:"<s:message code='editCat'/>",
  headerCatDel:"<s:message code='delCat'/>",
  headerCatUpdate:"<s:message code='header.cat.update'/>",
  headerCatView:"<s:message code='viewCat'/>",
  exportConfirm:"<s:message code='export.confirm'/>",
  importConfirm:"<s:message code='import.confirm'/>",
  delEntry:"<s:message code='delete.entry'/>",
  failedEntryEdit:"<s:message code='failed.entry.edit'/>",
  failedEntryCreate:"<s:message code='failed.entry.create'/>",
  delCat:"<s:message code='delete.cat'/>",
  confirmDelete:"<s:message code='confirm.delete'/>",
  confirmExit:"<s:message code='confirm.exit'/>",
  failedClipboard:"<s:message code='failed.clipboard'/>",
  successClipboard:"<s:message code='success.clipboard'/>",
  missingTitle:"<s:message code='missing.title'/>",
  urlInvalidFormat:"<s:message code='url.format.invalid'/>",
  ok:"<s:message code='ok'/>",
  yes:"<s:message code='yes'/>",
  no:"<s:message code='no'/>"
};
